language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install -e .
- pip install `python test/fit_requirements.py test/requirements.txt`
- pip install flake8 pytest-cov coveralls
script:
- | # flake8
  if python -c 'import sys; sys.version_info < (3, 3) or sys.exit(1)'
  then
    EXCLUDE=profiling/remote/asyncio.py
  fi
  flake8 profiling test setup.py \
    -v --show-source --ignore=E301 --exclude=$EXCLUDE
- | # pytest
  py.test -v --cov=profiling
after_success:
- coveralls
